version: '3.8'

services:
 web:
  build: .
  command: gunicorn Booking.wsgi -b 0.0.0.0:8000
  environment:
   - EMAIL_HOST_USER=abdullah.shaker2018@gmail.com
   - EMAIL_HOST_PASSWORD=sucess2018
  
  volumes:
   - .:/code
  ports:
   - 8000:8000
  depends_on:
   - db
 db:
  image: postgres:11
  environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  volumes:
   - postgres_data:/var/lib/postgresql/data/
volumes:
 postgres_data:
