# Generated by Django 3.1.5 on 2021-01-26 23:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_collection_collectiontitle'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collectiontitle',
            name='collection',
        ),
        migrations.AlterField(
            model_name='timeslot',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='slots', to='services.service'),
        ),
        migrations.DeleteModel(
            name='Collection',
        ),
        migrations.DeleteModel(
            name='CollectionTitle',
        ),
    ]
