# Generated by Django 3.1.5 on 2021-01-31 00:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('services', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointemts', to=settings.AUTH_USER_MODEL)),
                ('selected_slot', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='services.timeslot')),
            ],
        ),
    ]
